
version: '3.8'

services:
  translation-api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./translations:/app/translations
      - ./metadata:/app/metadata
      - ./vector_stores:/app/vector_stores
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
      - PORT=5000
      - DEBUG=true
